# Generated by Django 5.2.6 on 2025-09-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
    ]
