services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: storefront
      MYSQL_USER: django
      MYSQL_PASSWORD: djangopass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build:
      context: .
      # Switch this to 'production' for your prod deployment
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5555:5555"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: storefront
      DATABASE_USER: django
      DATABASE_PASSWORD: djangopass
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

volumes:
  mysql_data: